import { useEffect, useRef, useState, type CSSProperties } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { books, libraryLabels, librarySections } from '../../content/books'
export function LibraryNav() {
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const closeButton = useRef<HTMLButtonElement>(null)
  const selected = librarySections.find(section => section.id === selectedId)
  useEffect(() => { if (!selectedId) return; closeButton.current?.focus(); const close = (event: KeyboardEvent) => event.key === 'Escape' && setSelectedId(null); document.body.style.overflow = 'hidden'; window.addEventListener('keydown', close); return () => { document.body.style.overflow = ''; window.removeEventListener('keydown', close) } }, [selectedId])
  return <div className="library-nav"><div className="library-shelf">{librarySections.map(section => <motion.button key={section.id} layoutId={`library-${section.id}`} onClick={() => setSelectedId(section.id)} whileHover={{ y: -18 }} whileFocus={{ y: -10 }} className="library-spine" style={{ backgroundColor: section.color }} aria-label={`Open ${section.title}`}><span>{section.number}. {section.title}</span></motion.button>)}</div><AnimatePresence>{selected && <motion.div className="library-overlay" role="dialog" aria-modal="true" aria-labelledby="library-title" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.div layoutId={`library-${selected.id}`} className="library-book" style={{ '--library-accent': selected.color } as CSSProperties}><button ref={closeButton} className="library-back" onClick={() => setSelectedId(null)}>← {libraryLabels.back}</button><div className="library-spread"><div><span>{selected.number} / {libraryLabels.reading.toUpperCase()}</span><h2 id="library-title">{selected.heading}</h2><p>{selected.body}</p></div><ul>{selected.bookIds.map(id => { const book = books.find(item => item.id === id); return book && <li key={book.id}><i style={{ backgroundColor: book.spineColor }} /><div><strong>{book.title}</strong><span>{book.author}</span></div></li> })}</ul></div><button className="library-close" onClick={() => setSelectedId(null)} aria-label={libraryLabels.close}>×</button></motion.div></motion.div>}</AnimatePresence></div>
}
