import type { CaseStudyBlock } from '../../types/content'
import { bio } from '../../content/bio'
import { books } from '../../content/books'
import { personalTiles } from '../../content/personal'
import { principles } from '../../content/principles'
import { getBySlug } from '../../content/projects'
import { siteConfig } from '../../content/site'
import { ProjectVisual } from './ProjectVisual'
import { CornerBookshelf } from '../about/CornerBookshelf'
function ScrapbookBlock({ block, index }: { block: CaseStudyBlock; index: number }) { const label = `${String(index + 1).padStart(2, '0')} / ${block.beat.toUpperCase()}`; switch (block.kind) { case 'prose': return <article className="scrap-note scrap-prose"><span>{label}</span><h3>{block.heading}</h3>{block.paragraphs.map(p => <p key={p}>{p}</p>)}</article>; case 'quote': return <blockquote className="scrap-quote"><span>{block.label}</span>{block.quote}</blockquote>; case 'insight': return <article className="scrap-note scrap-insight"><span>{label}</span><h3>{block.heading}</h3>{block.intro && <p>{block.intro}</p>}<div>{block.insights.map(x => <section key={x.label}><b>{x.label}</b><p>{x.statement}</p></section>)}</div></article>; case 'decision': return <article className="scrap-note scrap-decision"><span>{label}</span><h3>{block.heading}</h3><dl><div><dt>THE TENSION</dt><dd>{block.difficulty}</dd></div><div><dt>THE MOVE</dt><dd>{block.proposal}</dd></div><div><dt>THE COST</dt><dd>{block.tradeoff}</dd></div></dl></article>; case 'outcome': return <article className="scrap-note scrap-outcome"><span>{label}</span><h3>{block.heading}</h3><p>{block.body}</p>{block.unverifiedNote && <small>{block.unverifiedNote}</small>}</article>; case 'reflection': return <article className="scrap-note scrap-reflection"><span>{label}</span><h3>{block.heading}</h3><p>{block.body}</p></article>; case 'figure': return <figure className="scrap-figure"><img src={block.media.src} alt={block.media.alt} width={block.media.width} height={block.media.height} />{block.caption && <figcaption>{block.caption}</figcaption>}</figure> } }
function ProjectScrapbook({ slug }: { slug: string }) { const project = getBySlug(slug); if (!project) return null; return <div className="scrapbook-content"><header className="scrap-project-header"><div><span>{project.year} · {project.status}</span><h2>{project.title}</h2><p>{project.outcome}</p></div><div className="scrap-project-art"><ProjectVisual artKey={project.artKey} accent={project.accent} scale="card" /></div><dl><div><dt>ROLE</dt><dd>{project.role}</dd></div><div><dt>TEAM</dt><dd>{project.team}</dd></div><div><dt>PLATFORM</dt><dd>{project.platform}</dd></div></dl></header><div className="scrap-blocks">{project.blocks.map((block, index) => <ScrapbookBlock block={block} index={index} key={block.id} />)}</div></div> }
function LifeScrapbook() { return <div className="scrapbook-content life-scrapbook"><header className="scrap-title"><span>FIELD NOTES / RECENTLY</span><h2>Things I make time for.</h2><p>No professional lesson attached. Just a few things that make life feel full.</p></header><CornerBookshelf /><div className="scrap-photo-board">{personalTiles.map((tile, index) => <article className={`scrap-polaroid rotate-${index}`} key={tile.id} style={{ backgroundColor: tile.media.placeholder }}><div>{tile.label} PHOTO</div><h3>{tile.headline}</h3><p>{tile.caption}</p></article>)}</div><section className="scrap-reading"><span>ON THE SHELF</span><div>{books.map(book => <article key={book.id} style={{ borderColor: book.spineColor }}><h3>{book.title}</h3><p>{book.author}</p><small>{book.status}</small></article>)}</div></section></div> }
function AboutScrapbook() { return <div className="scrapbook-content about-scrapbook"><header className="scrap-title"><span>AUTHOR / COLOPHON</span><h2>{bio.oneLine}</h2><p>{bio.long}</p></header><div className="scrap-portrait" style={{ backgroundColor: bio.portrait.placeholder }}><span>PORTRAIT</span></div><div className="scrap-bio">{bio.narrative.map(p => <p key={p}>{p}</p>)}</div><section className="scrap-principles">{principles.map((x, i) => <article key={x.id}><span>0{i + 1}</span><h3>{x.title}</h3><p>{x.body}</p></article>)}</section><footer className="scrap-contact"><span>WRITE TO ME</span><a href={`mailto:${siteConfig.email}`}>{siteConfig.email} ↗</a></footer></div> }
export function ScrapbookSpread({ bookId }: { bookId: string }) { if (bookId === 'systems') return <ProjectScrapbook slug="atlas" />; if (bookId === 'products') return <ProjectScrapbook slug="northstar" />; if (bookId === 'notes') return <LifeScrapbook />; return <AboutScrapbook /> }
