import { motion } from 'framer-motion'
import { RotateCcw } from 'lucide-react'
import { MAPPING_TABLE, isFlipAvailable, type GameState, type UnoFlipCard } from '@/games/uno-flip'

export interface FlipCardControlProps { readonly card: UnoFlipCard; readonly available: boolean; readonly onTrigger: () => void }
export function FlipCardControl({ card, available, onTrigger }: FlipCardControlProps) { return <button type="button" disabled={!available} onClick={onTrigger} className="mt-7 rounded-xl border-2 border-[#7250ad] bg-[#7250ad] p-5 text-left text-white disabled:cursor-not-allowed disabled:opacity-45"><p className="font-mono text-xs font-bold">{card.icon} FLIP</p><p className="mt-3 text-sm leading-6">{available ? 'Available once. Use it before or after revealing the first card.' : 'Unavailable for this turn.'}</p></button> }
export function Scoreboard({ state }: { readonly state: GameState }) { return <dl className="mt-8 grid grid-cols-3 gap-3 border-y border-black/15 py-5"><div><dt className="font-mono text-[8px] uppercase">Moves</dt><dd className="font-serif text-3xl">{state.moves}</dd></div><div><dt className="font-mono text-[8px] uppercase">Pairs</dt><dd className="font-serif text-3xl">{state.matches}/{state.grid.pairCount}</dd></div><div><dt className="font-mono text-[8px] uppercase">Side</dt><dd className="mt-2 font-mono text-xs uppercase">{state.grid.side}</dd></div></dl> }
export function MappingTable() { return <section className="mt-7"><p className="font-mono text-[8px] uppercase tracking-widest">Light ↔ Dark</p><div className="mt-3 space-y-2">{MAPPING_TABLE.map((row) => <div key={row.light} className="flex justify-between border-b border-dashed border-black/15 pb-1 font-mono text-[9px]"><span>{row.light}</span><span>→</span><span>{row.dark}</span></div>)}</div></section> }
export function WinPanel({ state }: { readonly state: GameState }) { if (state.status !== 'complete') return null; return <motion.div className="mt-7 border border-black/20 bg-white/70 p-5 text-center" initial={{ opacity:0,y:12 }} animate={{ opacity:1,y:0 }}><p className="font-serif text-3xl">Shelf cleared.</p><p className="mt-2 text-sm">All pairs matched in {state.moves} moves.</p></motion.div> }
export function SpreadRight({ state, onTriggerFlip, onReset }: { readonly state: GameState; readonly onTriggerFlip: () => void; readonly onReset: () => void }) { return <aside className="flex flex-col bg-black/[.035] p-8 pt-20 md:p-10 md:pt-24"><p className="font-mono text-[9px] uppercase tracking-[.2em]">Game index / seeded {state.grid.seed}</p><h2 id="uno-title" className="mt-5 font-serif text-5xl leading-none">UNO Flip<br/><em>Match.</em></h2><Scoreboard state={state}/><FlipCardControl card={state.grid.flipCard} available={isFlipAvailable(state)} onTrigger={onTriggerFlip}/><MappingTable/><WinPanel state={state}/><button onClick={onReset} className="mt-auto flex w-fit items-center gap-2 pt-8 font-mono text-[9px] uppercase tracking-widest"><RotateCcw size={14}/> New seeded game</button></aside> }
