'use client'
import { motion } from 'framer-motion'
import { ChevronLeft, ChevronRight, Download, Mail, X } from 'lucide-react'
import { profile, projects, type ModalView } from '@/data/content'
interface Props { activeModal: ModalView; selectedProject: string | null; onClose: () => void; onSelectProject: (id: string) => void }
export function BookSpreadModal({ activeModal, selectedProject, onClose, onSelectProject }: Props) {
  const index = Math.max(0, projects.findIndex(project => project.id === selectedProject)); const project = projects[index]
  return <motion.div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur-md" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} role="dialog" aria-modal="true" aria-labelledby="modal-title"><motion.article className="open-book relative grid max-h-[90vh] min-h-[620px] w-full max-w-6xl grid-cols-1 overflow-y-auto rounded-md shadow-2xl md:grid-cols-2" initial={{ scale: .92, y: 28 }} animate={{ scale: 1, y: 0 }} exit={{ scale: .95, y: 20 }} transition={{ type: 'spring', stiffness: 260, damping: 28 }}><button autoFocus onClick={onClose} className="absolute right-5 top-5 z-10 rounded-full border border-black/20 bg-white/70 p-2" aria-label="Close"><X size={18}/></button><div className="p-10 md:p-16"><span className="font-mono text-[10px] uppercase tracking-[.18em]">{activeModal} / Library volume</span><h2 id="modal-title" className="mt-10 font-serif text-5xl leading-none md:text-7xl">{activeModal === 'work' ? project.title : activeModal === 'about' ? 'Engineer by training. Designer by practice.' : activeModal === 'resume' ? 'Experience & capabilities.' : 'Let’s make sense of something together.'}</h2></div><div className="flex flex-col justify-center bg-white/35 p-10 md:p-16">{activeModal === 'work' && <><span className="font-mono text-[10px] uppercase tracking-widest">{project.discipline}</span><p className="mt-8 text-lg leading-8">{project.summary}</p><div className="mt-12 flex gap-3"><button className="rounded-full border p-3" onClick={() => onSelectProject(projects[(index-1+projects.length)%projects.length].id)} aria-label="Previous project"><ChevronLeft/></button><button className="rounded-full border p-3" onClick={() => onSelectProject(projects[(index+1)%projects.length].id)} aria-label="Next project"><ChevronRight/></button></div></>}{activeModal === 'about' && <p className="text-lg leading-8">{profile.about}</p>}{activeModal === 'resume' && <><p className="text-lg leading-8">Product architecture · Design systems · Zero-to-one product design · Interaction design · Product strategy</p><button onClick={() => window.print()} className="mt-10 flex w-fit items-center gap-2 rounded-full bg-ink px-5 py-3 text-sm text-paper"><Download size={16}/> Download résumé</button></>}{activeModal === 'contact' && <a href={`mailto:${profile.email}`} className="flex items-center gap-3 text-xl underline underline-offset-8"><Mail/> {profile.email}</a>}</div></motion.article></motion.div>
}
