import type { CaseStudy } from '../../types/content'
export const atlas = { slug: 'atlas', title: 'Giving a growing product one shared language', outcome: 'A new foundation that aligned fragmented workflows, reduced repeated decisions, and helped teams build with confidence.', disciplines: ['design-system', 'product-architecture'], year: '2025', status: 'shipped', artKey: 'atlas', accent: '#cbd6ff', featured: true, order: 1, role: 'Lead product designer', team: '3 designers, 8 engineers, product leads', timeline: '8 months', platform: 'Web + mobile', nextSlug: 'northstar', blocks: [
  { id: 'atlas-situation', kind: 'prose', beat: 'situation', heading: 'Growth had created more decisions than the product could hold.', paragraphs: ['The product had expanded quickly across multiple teams. Each team solved immediate needs independently, leaving users to relearn familiar interactions and engineers maintaining several versions of the same patterns.', 'The inconsistency was visible, but the deeper problem was structural: there was no shared model for how the product should behave.'] },
  { id: 'atlas-problem', kind: 'quote', beat: 'problem', label: 'THE REAL PROBLEM', quote: 'We didn’t just need consistent screens. We needed a shared understanding of the product underneath them.' },
  { id: 'atlas-analysis', kind: 'insight', beat: 'analysis', heading: 'Finding the patterns beneath the interface.', intro: 'I mapped core journeys, audited recurring patterns, and compared how teams had solved similar user needs.', insights: [{ label: 'WE STARTED WITH', statement: 'A request to standardise the interface.' }, { label: 'WE LEARNED', statement: 'Similar workflows used different logic and language.' }, { label: 'SO THE PROBLEM BECAME', statement: 'Align product behaviour, not just components.' }] },
  { id: 'atlas-decision', kind: 'decision', beat: 'decision', heading: 'One shared model, with room for variation.', difficulty: 'Teams served different users and worried that standardisation would remove necessary flexibility.', proposal: 'A common interaction model with defined extension points for genuine product-specific needs.', tradeoff: 'A shared model reduced local freedom, so extension points had to be explicit and governed.' },
  { id: 'atlas-outcome', kind: 'outcome', beat: 'outcome', heading: 'A clearer experience. A stronger foundation.', body: 'The work gave product and engineering teams a shared language for making decisions. It established reusable patterns, clarified ownership, and created a foundation the product could continue to grow from.', unverifiedNote: 'Replace this section with verified metrics and specific team outcomes before publishing.' },
  { id: 'atlas-reflection', kind: 'reflection', beat: 'reflection', heading: 'What I’d do differently.', body: 'Governance conversations should start alongside the initial audit—not after the first components ship. Beginning earlier would make ownership clearer and reduce avoidable revision.' },
] } satisfies CaseStudy
