import type { CaseStudy } from '../../types/content'
export const northstar = { slug: 'northstar', title: 'Turning an early idea into a product people could trust', outcome: 'From the first product model to the core experience: shaping a complex financial tool around clarity and control.', disciplines: ['founding-design', 'product-design'], year: '2024', status: 'concept', artKey: 'northstar', accent: '#ffb99f', featured: true, order: 2, role: 'Founding designer', team: 'Founders, product, and engineering', timeline: '0→1 product', platform: 'Strategy + execution', nextSlug: 'atlas', blocks: [
  { id: 'northstar-situation', kind: 'prose', beat: 'situation', heading: 'The idea was promising. The product model was still open.', paragraphs: ['The team saw an opportunity to make an intimidating financial task feel more manageable, but early concepts mixed education, account activity, and transactions without a clear hierarchy.', 'Before designing screens, I worked with the founders to define who the product was for, the decisions it needed to support, and the smallest experience that could earn trust.'] },
  { id: 'northstar-problem', kind: 'quote', beat: 'problem', label: 'THE PRODUCT QUESTION', quote: 'How might we give people enough context to act confidently—without making every decision feel like homework?' },
  { id: 'northstar-analysis', kind: 'insight', beat: 'analysis', heading: 'Trust came from control, not more information.', intro: 'Concept testing showed that people did not need another dense financial dashboard.', insights: [{ label: 'PEOPLE NEEDED', statement: 'A plain-language view of their current position.' }, { label: 'THE PRODUCT NEEDED', statement: 'A focused path from understanding to action.' }, { label: 'THE TEAM NEEDED', statement: 'A model that could grow without changing its centre.' }] },
  { id: 'northstar-decision', kind: 'decision', beat: 'decision', heading: 'Design the journey before the dashboard.', difficulty: 'The dashboard was the most tangible idea, but it depended on decisions the team had not made yet.', proposal: 'Define the primary task and its states first, then let the home experience support that journey.', tradeoff: 'We delayed a visually impressive dashboard to resolve the less visible product logic first.' },
  { id: 'northstar-outcome', kind: 'outcome', beat: 'outcome', heading: 'A product direction the team could build from.', body: 'The work translated an early proposition into a testable product model, a focused core journey, and a reusable visual foundation.', unverifiedNote: 'Add verified launch, activation, or research outcomes here before publishing.' },
  { id: 'northstar-reflection', kind: 'reflection', beat: 'reflection', heading: 'What I’d carry forward.', body: 'In zero-to-one work, visual polish can make an unresolved idea look deceptively complete. The strongest progress came when we kept returning to the product model and treated the interface as evidence of those decisions.' },
] } satisfies CaseStudy
